### ISSUE TITLE
Link do zemljevida

### ISSUE THREAD

**Issue by matevzraspet** [matevzraspet/APPR-2017-18#4]
Zanima me kako dobim ta link za uvoz zemljevida in kaj pomeni tam SVN_adm1 , primer. :
 gpclibPermit()
zemljevid <- uvozi.zemljevid("http://biogeo.ucdavis.edu/data/gadm2.8/shp/SVN_adm_shp.zip",
                             "SVN_adm1", encoding = "UTF-8") %>% pretvori.zemljevid()

Sam bi rad namreč vnesel takšen zemljevid : https://gadm.org/maps/DEU_1.html.
Se pravi zemljevid Nemčije s pokrajinami.

Hvala za pomoč.

**Comment by jaanos** [comment]
Zemljevid v obliki SHP dobiš iz gadm.org, če klikneš na *DATA* in potem poiščeš Nemčijo med državami. Potem lahko uporabiš funkcijo `uvozi.zemljevid`:
```R
zemljevid <- uvozi.zemljevid("https://biogeo.ucdavis.edu/data/gadm3.6/shp/gadm36_DEU_shp.zip",
                             "gadm36_DEU_1") %>% pretvori.zemljevid()
```

**Comment by jaanos** [comment]
Drugi argument funkcije `uvozi_zemljevid` je ime datoteke v arhivu (brez končnice), ki vsebuje želeni zemljevid (na zgornji povezavi je torej arhiv, ki med drugim vsebuje datoteko `gadm36_DEU_1.shp` in druge datoteke z istim imenom in drugimi končnicami).
