### ISSUE TITLE
Zemljevid

### ISSUE THREAD

**Issue by matevzraspet** [matevzraspet/APPR-2017-18#5]
Pozdravljeni,
nevem zakaj v tej kodi javlja neko napako: 

slovenija <- uvozi.zemljevid("http://baza.fmf.uni-lj.si/OB.zip",
                          "OB/OB", encoding = "UTF-8") %>%
  pretvori.zemljevid()

placa_2010 <- ggplot() + geom_polygon(data = placa1 %>% 
                                       right_join(slovenija, by = c("obcina" = "NAME_1")),
                                     aes(x = long, y = lat, group = group, fill = dohodek)) +
                                      ggtitle("Povprečna plača v letu 2010 po občinah")

Rad bi namreč iz tabele placa1 v vajasprint.r pobarval občine Slovenije glede na velikost dohodka v posmezni regiji.
Hvala za pomoč.

**Comment by jaanos** [comment]
V zemljevidu slovenskih občin so imena stolpcev drugačna kot v zemljevidih iz gadm.org. Najbolje  bo, da kar pogledaš, kateri stolpci so na voljo - zate verjetno pride v upoštev `OB_IME` ali `OB_UIME`.
