### ISSUE TITLE
Zaključek projekta

### ISSUE THREAD

**Issue by matevzraspet** [matevzraspet/APPR-2017-18#7]
Pozdravljeni,
projekt sem zaključil in ga pošiljam v pogled.

Zanima pa me še en malenkosten popravek.  
Na domačem računalniku mi v tabeli placa šumnike ne izpisuje pravilno, tako da se ime občine,ki vsebuje šumnik ne ujema z imenom občine na zemljevidu, zato mi le te obarva sivo( mi ne vključi podatka višine plače). V šoli pa je delalo pravilno.
Kako bi to lahko  popravil?

Lep pozdrav.

**Comment by jaanos** [comment]
Poročilo se prevede, tako da bom dodal povezavo na repozitorij za zagovore, z @alenFMF pa se lahko domeniš za termin zagovora (če se seveda še nisi). Če boš še kaj spreminjal, mi prosim javi, da posodobim povezavo.

Bi pa opozoril, da pri napredni analizi podatkov ni tega, kar bi pričakoval - torej vsaj kakšnega modela (korelacije med podatki) ali razvrščanja v skupine. Shiny aplikacija je načeloma koristno orodje za odkrivanje zanimivih možnosti za analizo, a zagotovo mora ta biti izvedena na ustreznih podatkih skupaj z razlago (ne pa, da se mora uporabnik sam dokopati do morebitnih zaključkov). Poleg tega so podatki, ki jih prikazuješ v Shiny aplikaciji, povsem nepovezani z ostalimi podatki, s katerimi delaš.

Kar se šumnikov tiče, nisem prepričan, zakaj pri tebi ne delujejo - kodiranje znakov namreč podaš tako pri uvozu razpredelnice `placa` kot pri uvozu zemljevida. Če prav razumem, se šumniki v zemljevidu pravilno uvozijo, v tabeli `placa` pa ne? Kako se ti pa izpišejo?

**Comment by matevzraspet** [comment]
Zmenjeno, bom potem popravil in nadgradil napredno analizo podatkov.
V zemljevidu se šumniki izpišejo pravilno, v plači pa se č nadomesti s c.

**Comment by jaanos** [comment]
Poskusi izvesti sledeče ukaze enega po enega:

https://github.com/matevzraspet/APPR-2017-18/blob/f491911ed3411f561c5219776ef3308baf1d686f/uvoz/vajasprint.r#L143-L149

Po vsakem preveri, ali se v razpredelnici `placa` šumniki pravilno izpišejo - tako boš ugotovil, kje natanko se pojavi problem.

**Comment by matevzraspet** [comment]
Vrstica :
placa$obcina <- placa$obcina %>% strapplyc("^([^/]*)") %>% unlist()
zmede šumnike.

**Comment by jaanos** [comment]
Predlagam, da najprej poskusiš pred zgornjo vrstico postaviti še
```R
Encoding(placa$obcina) <- "UTF-8"
```
Če ne bo pomagalo, pa jo poskusi nadomestiti z
```R
placa$obcina <- gsub("/.*$", "", placa$obcina) #nadomesti vse od / do konca vrstice s praznim nizom
```
